### PR TITLE
Add the files for compiling the lucuma themes and for publishing

### PR DESCRIPTION
**Pull request by toddburnside**
This is the addition of the lucuma-themes and the machinery for building and publishings the themes from `lucuma-primereact-designer` on top of fork from the `primereact-sass-theme` repository. Since the primereact themes are now public, our repository can also be public. This should make it easier to update our themes based on new versions of primereact.

### CODE REVIEW

**Comment by toddburnside** [comment]
@armanbilge Could you take a quick look at this, please. I essentially just copied the sbt and some other files from the `lucuma-primereact-designer` repo (with some version upgrades). The goal is to be able the publish the themes with the same name as before, although I did bump the version.

Also, is there a better way to manage this as a fork? As it currently is, we'll need to mindful of not making PRs against the upstream primefaces repository, since that is the default. Maybe we can use a different branch as our "main" or something?

**Comment by armanbilge** [comment]
> Also, is there a better way to manage this as a fork? As it currently is, we'll need to mindful of not making PRs against the upstream primefaces repository, since that is the default. Maybe we can use a different branch as our "main" or something?

We can actually "unfork" this repo, such that GitHub no longer knows about the relationship to the upstream. Would that help? On the other hand, it would make it harder to track the upstream if that's important.

**Comment by armanbilge** [comment]
> I essentially just copied the sbt and some other files from the `lucuma-primereact-designer` repo (with some version upgrades).

This looks good to me 👍 

---

> This should make it easier to update our themes based on new versions of primereact.

If we decide to unfork, maybe we can add a workflow to this repository that automatically opens a PR merging upstream changes.

---

Actually, another option instead of forking, I wonder if we could just manage the upstream as a git submodule in this repository. Then we could get dependabot updates of that for free.

**Comment by toddburnside** [comment]
> > I essentially just copied the sbt and some other files from the `lucuma-primereact-designer` repo (with some version upgrades).
> 
> This looks good to me 👍
> 
> > This should make it easier to update our themes based on new versions of primereact.
> 
> If we decide to unfork, maybe we can add a workflow to this repository that automatically opens a PR merging upstream changes.
> 
> Actually, another option instead of forking, I wonder if we could just manage the upstream as a git submodule in this repository. Then we could get dependabot updates of that for free.

@armanbilge These are good ideas. Would you be willing to take this task on? I think the only files in the upstream we should ever need to modify are `.gitignore` and `package.json` (because we need `sass` to build the themes).

**Comment by armanbilge** [comment]
Yeah, I'll work on it! Which approach did you prefer?

**Review by cquiroz — APPROVED** [review]
LGTM

**Pull request merged**
